# Default values for llama-stack-operator
# This chart deploys cluster-wide resources (CRD, operator)

operator:
  image: quay.io/eformat/llama-stack-k8s-operator:v0.3.0
  namespace: llama-stack-k8s-operator-controller-manager
