# Default values for llama-stack
# This is a YAML-formatted file.

granite:
  modelName: granite-3dot2-8b-instruct
  endpoint: ""
  apiToken: ""
  tlsverify: true

llamaguard:
  modelName: llama-guard-3-1b
  endpoint: ""
  apiToken: ""
  tlsverify: true

llamaStack:
  image: llamastack/distribution-remote-vllm:latest
  name: rh-dev
namespace: lls-demo
